Disable ESS-specific session workaround by default
inrupt/solid-client-authn-js pull request #1290
Opened 2021-04-21 14:57 UTC by Vinnl

The calls to /session that resulted in 404s were confusing to
developers, and a less brittle workaround is now available with
`restorePreviousSession`. ESS has also disabled the option by
default.

- [x] I've added a unit test to test for potential regressions of this bug.
- [x] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-04-21 16:32 UTC, NSeydoux requested changes
There's one thing that would be good to add in this PR as part of disabling this behaviour by default: currently, the `fetch` function for `ClientAuthentication` is initialized to a locally defined `fetchWithCookies`, which is a regular fetch with `credentials: "include"`. Including credentials is only required in the case when we're relying on a cookie for authenticated fetch, and it's causing CORS issues in many cases where it's not providing any value. Ideally, in `Session.ts`, in the code dedicated to the workaround, if the ESS cookie is used for authentication then the session should override its `clientAuthentication`'s `fetch` with `fetchWithCookies`.

2021-04-21 16:34 UTC, Vinnl commented
Ah, gotcha - I'd assumed that was automatically avoided. Will change that tomorrow, thanks.

2021-04-22 10:51 UTC, Vinnl commented
OK, done in aa98bba39780cf7d35821e434a42054b7ecd3139.

2021-04-22 11:31 UTC, NSeydoux approved these changes

2021-04-28 09:21 UTC, merged