DOCS-166: update docs nav for dev-tools
inrupt/solid-client-authn-js pull request #323
Opened 2020-09-15 21:00 UTC by kay-kim

Update Docs top nav bar to have Developer Tools instead of Client Libraries to allow for SDK (also matches products page of company website)
<img width="483" alt="Screen Shot 2020-09-15 at 4 58 48 PM" src="https://user-images.githubusercontent.com/2126636/93264245-d4ff7580-f774-11ea-8c60-6cca69160998.png">

- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-09-16 07:47 UTC, Vinnl commented on packages/browser/docs/api/_templates/docs-navbar.html
> +                        <a href="{{theme_reactsdk_docs}}">JavaScript React SDK</a>
@kay-kim Given that https://github.com/inrupt/docs-client-lib-js/pull/9 says "Wait until next week", should this wait as well?

2020-09-16 13:42 UTC, Vinnl requested changes
Holding off until Sept 23rd to merge this.

2020-10-07 07:05 UTC, kay-kim commented
Oops -- forgot about this pull.  Ping @NSeydoux @Vinnl

2020-10-07 07:36 UTC, Vinnl approved these changes
Whoops, I'd set a reminder for solid-client, but not this one apparently.

2020-10-07 07:36 UTC, merged